server:
  port: 2004
spring:
  redis:
    database: 5
    host: 192.168.1.113
    port: 6379
    password: Password123
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qwerasdfzxcv123$%^
#    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://140.143.189.51:3306/body_temperature_cloud?useSSL=false&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
security:
  oauth2:
    client:
      client-id: auth
      client-secret: auth
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /login/**
        - /social/info/*
        - /mobile/*
        - /log/save
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true
auth:
  accessTokenValiditySeconds: 3600
  refreshTokenValiditySeconds: 10000000